2022-05-11 19:32:22,929 DEBUG :: Starting new HTTPS connection (1): testnet.binancefuture.com:443
2022-05-11 19:32:23,369 DEBUG :: https://testnet.binancefuture.com:443 "GET /fapi/v1/exchangeInfo HTTP/1.1" 200 None
2022-05-11 19:32:23,374 DEBUG :: Starting new HTTPS connection (1): testnet.binancefuture.com:443
2022-05-11 19:32:23,769 DEBUG :: https://testnet.binancefuture.com:443 "GET /fapi/v1/account?timestamp=1652277743374&signature=7ade67d7f5c8adb3219e3559195b842befbda897d0860c9f0288b011cd92d086 HTTP/1.1" 200 None
2022-05-11 19:32:23,769 INFO :: Binance Futures Client successfully initialized
2022-05-11 19:32:24,380 INFO :: Binance connection opened
2022-05-11 19:32:32,439 INFO :: Binance: subscribing to: btcusdt@bookTicker
2022-05-11 19:32:32,439 DEBUG :: Starting new HTTPS connection (1): testnet.bitmex.com:443
2022-05-11 19:32:33,406 DEBUG :: https://testnet.bitmex.com:443 "GET /api/v1/instrument/active HTTP/1.1" 200 None
2022-05-11 19:32:33,813 DEBUG :: Starting new HTTPS connection (1): testnet.bitmex.com:443
2022-05-11 19:32:34,168 DEBUG :: https://testnet.bitmex.com:443 "GET /api/v1/user/margin?currency=all HTTP/1.1" 200 None
2022-05-11 19:32:34,168 INFO :: Bitmex Client successfully initialized
2022-05-11 19:32:34,956 INFO :: Bitmex connection opened
2022-05-11 19:32:39,480 ERROR :: error from callback <bound method BinanceClient._on_close of <connectors.binance.BinanceClient object at 0x0000019351158CA0>>: _on_close() takes 2 positional arguments but 4 were given
2022-05-11 19:32:39,480 ERROR :: Binance connection error: _on_close() takes 2 positional arguments but 4 were given
2022-05-11 19:32:39,701 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x0000019351158CD0>>: _on_close() takes 2 positional arguments but 4 were given
2022-05-11 19:32:39,706 ERROR :: Bitmex connection error: _on_close() takes 2 positional arguments but 4 were given
